# Generated by Django 3.1.7 on 2021-02-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_keyword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
