# Generated by Django 3.1.7 on 2021-02-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0003_auto_20210228_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_keyword',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_address',
            field=models.CharField(default='주소를 입력해주세요.', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_phone',
            field=models.CharField(default='전화번호를 입력해주세요.', max_length=40),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='shareRes.category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_content',
            field=models.TextField(default='맛집에 대해 더 소개해주세요.'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_link',
            field=models.CharField(default='맛집과 관련되 링크를 입력해주세요.', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(default='맛집 이름을 입력해주세요.', max_length=100),
        ),
    ]
